//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.App.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Company.App.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company App.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 1.
        /// </summary>
        public static string BottomTabBar_Item_Template1 {
            get {
                return ResourceManager.GetString("BottomTabBar_Item_Template1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 2.
        /// </summary>
        public static string BottomTabBar_Item_Template2 {
            get {
                return ResourceManager.GetString("BottomTabBar_Item_Template2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 3.
        /// </summary>
        public static string BottomTabBar_Item_Template3 {
            get {
                return ResourceManager.GetString("BottomTabBar_Item_Template3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection is not available..
        /// </summary>
        public static string Exception_NoInternetConnection {
            get {
                return ResourceManager.GetString("Exception_NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close side bar menu.
        /// </summary>
        public static string SideBar_CloseMenu {
            get {
                return ResourceManager.GetString("SideBar_CloseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open side bar menu.
        /// </summary>
        public static string SideBar_OpenMenu {
            get {
                return ResourceManager.GetString("SideBar_OpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 1.
        /// </summary>
        public static string SideBarMenu_Item_Template1 {
            get {
                return ResourceManager.GetString("SideBarMenu_Item_Template1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 2.
        /// </summary>
        public static string SideBarMenu_Item_Template2 {
            get {
                return ResourceManager.GetString("SideBarMenu_Item_Template2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 3.
        /// </summary>
        public static string SideBarMenu_Item_Template3 {
            get {
                return ResourceManager.GetString("SideBarMenu_Item_Template3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 1.
        /// </summary>
        public static string Template1_Title {
            get {
                return ResourceManager.GetString("Template1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 2.
        /// </summary>
        public static string Template2_Title {
            get {
                return ResourceManager.GetString("Template2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 3.
        /// </summary>
        public static string Template3_Title {
            get {
                return ResourceManager.GetString("Template3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string UserError_Dialog_Action_Ok {
            get {
                return ResourceManager.GetString("UserError_Dialog_Action_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        public static string UserError_Dialog_Message_Generic {
            get {
                return ResourceManager.GetString("UserError_Dialog_Message_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string UserError_Dialog_Tile {
            get {
                return ResourceManager.GetString("UserError_Dialog_Tile", resourceCulture);
            }
        }
    }
}
